tunefs.ocfs2: fix parallel build
Parallel build (make -j 10) sometimes fails with an error:

o2cluster.c:32:10: fatal error: o2ne_err.h: No such file or directory
 #include "o2ne_err.h"
          ^~~~~~~~~~~~
compilation terminated
make[2]: *** [../Postamble.make:40: o2cluster.o] Error 1

So add a missing depends for o2cluster.o on o2ne_err.h.