Define _DEFAULT_SOURCE to get loff_t
Since glibc 2.28 either _DEFAULT_SOURCE or _GNU_SOURCE is required
to get loff_t defined again.

In file included from o2cb_abi.c:52:
../include/ocfs2/ocfs2.h:222:2: error: unknown type name 'loff_t'
  loff_t d_off; /* Offset of structure in the file */
  ^~~~~~